// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/23/2025, 5:51:48 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/harendra-shah/programe/NuxtProject1/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/harendra-shah/programe/NuxtProject1/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/harendra-shah/programe/NuxtProject1/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/harendra-shah/programe/NuxtProject1/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/harendra-shah/programe/NuxtProject1/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/harendra-shah/programe/NuxtProject1/plugins/**/*.{js,ts,mjs}","/home/harendra-shah/programe/NuxtProject1/composables/**/*.{js,ts,mjs}","/home/harendra-shah/programe/NuxtProject1/utils/**/*.{js,ts,mjs}","/home/harendra-shah/programe/NuxtProject1/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/harendra-shah/programe/NuxtProject1/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/harendra-shah/programe/NuxtProject1/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;