// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/23/2025, 7:46:36 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/harendra-shah/programe/vite/task2login/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/harendra-shah/programe/vite/task2login/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/harendra-shah/programe/vite/task2login/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/harendra-shah/programe/vite/task2login/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/harendra-shah/programe/vite/task2login/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/harendra-shah/programe/vite/task2login/plugins/**/*.{js,ts,mjs}","/home/harendra-shah/programe/vite/task2login/composables/**/*.{js,ts,mjs}","/home/harendra-shah/programe/vite/task2login/utils/**/*.{js,ts,mjs}","/home/harendra-shah/programe/vite/task2login/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/harendra-shah/programe/vite/task2login/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/harendra-shah/programe/vite/task2login/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;